# Generated by Django 4.2.27 on 2026-03-06 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About Us'},
        ),
    ]
