# Generated by Django 4.2.27 on 2026-03-06 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_aboutus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='chairman_message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='chairman_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='chairman_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='message_title',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
