# Generated by Django 4.2.27 on 2026-03-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aboutus_chairman_message_aboutus_chairman_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='clients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='companies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
