# Generated by Django 4.2.27 on 2026-03-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_companycard_rename_name_company_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
