# Generated by Django 4.2.27 on 2026-03-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_company_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycard',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
