# Generated by Django 4.2.27 on 2026-03-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_gallerycategory_gallerytags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'verbose_name_plural': 'Gallery Categories'},
        ),
        migrations.AlterModelOptions(
            name='gallerytags',
            options={'verbose_name_plural': 'Gallery Tags'},
        ),
    ]
